### ISSUE TITLE
punishment DMs

### ISSUE THREAD

**Issue by Lander-P** [ModuloBot/Tracker#25]
Hey!
Can you please make the bot send the ban/kick reason?
It will make everything easier!

**Comment by LanderP04** [comment]
And -clear looks better in the server log channel

**Comment by NovusTheory** [comment]
I prefer not using DM's as they have a chance to fail and I will not program the bot to perform retries. While other bots do this and it may seem fine. They do have a chance due to a user's privacy setting to not be performed and thus make the DM worthless. I personally keep mine disabled so no bot can do this to me. I personally hate bot's that DM you so this is an unlikely feature that will happen.

As for `-clear` this is a separate issue in itself :)

**Comment by Ar3n5** [comment]
> Hey!
> Can you please make the bot send the ban/kick reason?
> It will make everything easyer!

easier?
